In [4]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

columns = [
    "class",
    "age",
    "sex",
    "steroid",
    "antivirals",
    "fatigue",
    "malaise",
    "anorexia",
    "liver_big",
    "liver_firm",
    "spleen_palpable",
    "spiders",
    "ascites",
    "varices",
    "bilirubin",
    "alk_phosphate",
    "sgot",
    "albumin",
    "prothrombin_time",
    "histology"
]
df = pd.read_csv('../data_raw/hepatitis/hepatitis.csv', header=None, names=columns)
df = df.replace('?', np.nan)
df.head()

,class,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,prothrombin_time,histology
0,2,30,2,1,2,2,2,2,1,2,2,2,2,2,1.00,85,18,4.0,NaN,1
1,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,NaN,1
2,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,NaN,1
3,2,31,1,NaN,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,NaN,200,4.0,NaN,1

In [5]:
binary_cols = [
    "sex",
    "steroid",
    "antivirals",
    "fatigue",
    "malaise",
    "anorexia",
    "liver_big",
    "liver_firm",
    "spleen_palpable",
    "spiders",
    "ascites",
    "varices",
    "histology"]

numeric_cols = [x for x in df.columns if x not in binary_cols and x != "class"]

# numeric imputer (mean)
num_imputer = SimpleImputer(strategy='mean')
df[numeric_cols] = num_imputer.fit_transform(df[numeric_cols])

# categorical imputer (most frequent)
cat_imputer = SimpleImputer(strategy='most_frequent')
df[binary_cols] = cat_imputer.fit_transform(df[binary_cols])

for col in binary_cols:
    df[col] = df[col].astype(int).map({1: 1, 2: 0})
df["class"] = df["class"].astype(int).map({1: 1, 2: 0})

In [6]:
df.head()

,class,age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,prothrombin_time,histology
0,0,30.0,0,1,0,0,0,0,1,0,0,0,0,0,1.0,85.000000,18.0,4.0,61.852273,1
1,0,50.0,1,1,0,1,0,0,1,0,0,0,0,0,0.9,135.000000,42.0,3.5,61.852273,1
2,0,78.0,1,0,0,1,0,0,0,0,0,0,0,0,0.7,96.000000,32.0,4.0,61.852273,1
3,0,31.0,1,0,1,0,0,0,0,0,0,0,0,0,0.7,46.000000,52.0,4.0,80.000000,1
4,0,34.0,1,0,0,0,0,0,0,0,0,0,0,0,1.0,105.325397,200.0,4.0,61.852273,1

In [7]:
df.to_csv("../data_cleaned/hepatitis_imputed.csv", index=False)